# Generated by Django 4.1.7 on 2023-03-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total_sum',
            field=models.FloatField(default=2.0),
        ),
    ]
